baseURL = 'http://youzipi.org/'
buildFuture = true
title = 'youzipi'

languageCode = "zh-cn"
DefaultContentLanguage = "zh-cn"
hasCJKLanguage = true

theme = 'mainroad'

paginate = "10" # Number of posts per page
disqusShortname = "youzipi" # Enable comments by entering your Disqus shortname
googleAnalytics = "G-32BLR3ZEP9" # Enable Google Analytics by entering your tracking id

enableGitInfo = true

[markup]
  # defaultMarkdownHandler = 'blackFriday'
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    hardWraps = true
  # [markup.blackFriday]
  #   hrefTargetBlank = true
  #   extensions = ["hardLineBreak"] # 解决 中文换行变空格 的问题
  [markup.tableOfContents]
    endLevel = 10
    ordered = false
    startLevel = 1 # 默认是从 h2 开始
  


[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = [":git", "lastmod", ":fileModTime", "date", "publishDate"]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]

[permalinks]
  # blog = "/blog/:year/:month/:day/:filename/"
  blog = "/blog/:year/:filename/"
  docs = "/:filename/"


[Author]
  name = "youzipi"
  bio = "没有一天应该被牺牲"
  avatar = "img/avatar.jpg"


# 在顶部添加菜单栏，weight 决定显示顺序
[menu]
    [[menu.main]]
        identifier = "blog"
        name = "blog"
        url = "/blog/"
        weight = 10
    [[menu.main]]
      identifier = "archives"
      name = "archives"
      url = "/archives/"
      weight = 15
    [[menu.main]]
        identifier = "categories"
        name = "categories"
        url = "/categories/"
        weight = 20
    [[menu.main]]
        identifier = "tags"
        name = "tags"
        url = "/tags/"
        weight = 30
    [[menu.main]]
        identifier = "about"
        name = "about"
        url = "/about/"
        weight = 40

[Params]
  description = "youzipi's blog" # Description of your site
  opengraph = true
  schema = true
  twitter_cards = false
  readmore = true # Show "Read more" button in list if true
  authorbox = false
  pager = true
  post_meta = ["author", "date", "categories"] # Order of post meta information
  mainSections = ["blog"]
  toc = true
   # 版权声明
  copyright = "youzipi"

  
  gitRepo = "git@github.com:youzipi/youzipi.github.io.git"


  dateFormatToUse = "2006-01-02"

  # show word count and read time ?                       # 是否显示字数统计与阅读时间
  moreMeta = true

  fancybox = true           # see https://github.com/fancyapps/fancybox                 # 是否启用 fancybox（图片可点击）

  
  # style
#   customCSS = [
# 	"https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css",
# ]

[Params.logo]
  image = "img/avatar.jpg"
  title = "youzipi"
  subtitle = "developer"

[params.reward]                                         # 文章打赏
  enable = false
  wechat = "/path/to/your/wechat-qr-code.png"           # 微信二维码
  alipay = "/path/to/your/alipay-qr-code.png"           # 支付宝二维码


[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist","social", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  categories_counter = true # Enable counter for each category in "Categories" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  # Enable parts of social widget
  # facebook = "username"
  twitter = "youzipi870"
  instagram = "wuyouzipi"
  # linkedin = "username"
  telegram = "youzipi"
  github = "youzipi"
  # gitlab = "username"
  # bitbucket = "username"
  email = "blake_12@qq.com"

[[Params.widgets.social.custom]]
  title = "douban"
  url = "https://www.douban.com/people/youzipi870/"
  # icon = "img/avatar.svg"


# style
[Params.style.vars]
  highlightColor = "#07a"
  # Override font-family sets
  # Take care of different quotes OR escaping symbols in these params if necessary
  fontFamilyPrimary = "'LXGW WenKai', Monaco, Consolas, 'Open Sans', Helvetica, Arial, sans-serif"
  # Secondary font-family set responsible for pre, code, kbd, and samp tags font
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

# [Params]


# maupassant

## utteranc
[Params.utteranc]
  enable = true
  repo = "youzipi/youzipi.github.io"    # 存储评论的 Repo，格式为 owner/repo
  issueTerm = "title"  #表示你选择以那种方式让 github issue 的评论和你的文章关联。
  theme = "github-light" # 样式主题，有 github-light 和 github-dark 两种

## cc
[Params.cc]
  name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
  link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

## busuanzi
[params]
  busuanzi = true


[[Params.links]]
  title = "github"
  name = "github"
  url = "https://github.com/youzipi"
